apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: heyo971px-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: heyo971px-go 
  name: heyo971px-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: heyo971px-go 
